# Site settings
title: Starry
description: > # this means to ignore newlines until "baseurl:"
 starry's blog<br>©2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://b.starry.gq" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
