# Site settings
title: Starry
author: Starry
description: > # this means to ignore newlines until "baseurl:"
 Starry's blog<br>©2018
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.imlyh.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
